# AUTOGENERATED! DO NOT EDIT! File to edit: 01_table_builders.ipynb (unless otherwise specified).

__all__ = ['payroll_issues_builder']

# Cell
import pandas as pd

# Cell
def payroll_issues_builder(payern):
    """Create payroll issues table
    Args:
        payern (DataFrame): pay earnings table (or snapshot)
    """

    payroll_issues = payern.pivot_table(
        values=['is_finalized', 'is_late'],
        aggfunc={'is_finalized':['count','sum','mean'],
                 'is_late':['sum','mean'],
                 },
        index=['EMPLID','EMPL_RCD','SUB_PAY_END_DT'])

    payoll_issues